version: "3.7"

services:
  eventstore:
    image: eventstore/eventstore:latest
    command: ["--ext-ip", "0.0.0.0", "--int-ip", "0.0.0.0", '--disable-internal-tcp-tls', '--disable-external-tcp-tls', "--disable-first-level-http-authorization", "--enable-external-tcp", "--dev", "--mem-db=false"]
    environment:
      #- EVENTSTORE_GOSSIP_SEED=172.18.0.12:2112,172.18.0.13:2112,172.18.0.14:2112,172.18.0.15:2112
      #- EVENTSTORE_NODE_PRIORITY=3
      #- EVENTSTORE_INT_IP=${SINGLE_NODE_MACHINE_IP}
      #- EVENTSTORE_EXT_IP=${SINGLE_NODE_MACHINE_IP}
      - EVENTSTORE_EXT_HTTP_PORT=2113
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_EXT_HTTP_PREFIXES=http://*:2113/
    ports:
      - 1113:1113
      - 2113:2113
    volumes:
      - "~/mold_encrypted/projects/app-fluke/data-eventstore/db:/var/lib/eventstore"
      - "~/mold_encrypted/projects/app-fluke/data-eventstore/logs:/var/log/eventstore"
    restart: always
    network_mode: host
