name: build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
          include-prerelease: true

      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - run: cd ./src/Fluke.UI.Frontend && yarn build:fable
      - run: cd ./src/Fluke.Shared.Tests && dotnet run
      - run: cd ./src/Fluke.UI.Frontend && yarn install
      - run: cd ./src/Fluke.UI.Frontend && yarn test
      - run: cd ./src/Fluke.UI.Frontend && yarn build:react
      - run: cd ./src/Fluke.UI.Frontend && yarn cypress-install
      - run: sudo apt-get install libnss3-tools

      - uses: cypress-io/github-action@v2
        with:
          working-directory: ./src/Fluke.UI.Frontend
          build: npx cypress info
          start: yarn frontend-serve
          command: yarn cypress-run


      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: ./src/Fluke.UI.Frontend/cypress/screenshots

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-videos
          path: ./src/Fluke.UI.Frontend/cypress/videos

  electron:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: samuelmeuli/action-electron-builder@v1

      - run: cd ./src/Fluke.UI.Frontend && yarn electron-build

      - uses: actions/upload-artifact@v2
        with:
          path: |
            ./src/Fluke.UI.Frontend/electron_output/*.exe
            ./src/Fluke.UI.Frontend/electron_output/*.zip
            ./src/Fluke.UI.Frontend/electron_output/*.AppImage
            ./src/Fluke.UI.Frontend/electron_output/*.snap
          if-no-files-found: error

  push:
    needs: electron
    runs-on: ubuntu-latest
    steps:
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./src/Fluke.UI.Frontend/cra_output
