name: build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - uses: actions/setup-node@v2
        with:
          node-version: 15

      - run: cd ./src/Fluke.UI.Frontend && yarn build:fable
      - run: cd ./test/Fluke.Shared.Tests && dotnet run
      - run: cd ./src/Fluke.UI.Frontend && yarn install
      - run: cd ./src/Fluke.UI.Frontend && yarn test
      - run: cd ./src/Fluke.UI.Frontend && yarn build:react
      - run: cd ./src/Fluke.UI.Frontend && yarn cypress-install
      - run: sudo apt-get install libnss3-tools

      - uses: cypress-io/github-action@v2
        with:
          working-directory: ./src/Fluke.UI.Frontend
          build: npx cypress info
          start: yarn frontend-serve
          wait-on: https://localhost:33922
          wait-on-timeout: 120
          command: yarn cypress run --headed --browser chrome

      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: ./src/Fluke.UI.Frontend/cypress/screenshots

      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-videos
          path: ./src/Fluke.UI.Frontend/cypress/videos

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./src/Fluke.UI.Frontend/build
