name: build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - uses: actions/setup-node@v2
        with:
          node-version: '15'

      - run: cd ./test/Fluke.Shared.Tests && dotnet tool restore && dotnet paket restore && dotnet run
      - run: cd ./src/Fluke.UI.Frontend && yarn install
      - run: cd ./src/Fluke.UI.Frontend && yarn test
      - run: cd ./src/Fluke.UI.Frontend && yarn build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./src/Fluke.UI.Frontend/build
